### PR TITLE
Upgrade CRDs to apiextensions.k8s.io/v1

### PR DESCRIPTION
**Pull request by stefanprodan**
Ref: https://github.com/fluxcd/toolkit/issues/111

### CODE REVIEW

**Comment by stefanprodan** [comment]
I prefer to run the e2e tests on the latest stable version instead of the lowest supported. If you want to test on all versions then we should do a matrix out of all Kubernetes supported versions e.g. 1.16/17/18

**Comment by hiddeco** [comment]
> If you want to test on all versions then we should do a matrix out of all Kubernetes supported versions e.g. 1.16/17/18

Ack. In case of a matrix, I would only run all versions for `master` builds.

**Comment by stefanprodan** [comment]
> Ack. In case of a matrix, I would only run all versions for master builds.

That's not possible with GH Actions, we could duplicate the whole workflow for PRs but then we need to keep them in sync.

**Comment by hiddeco** [comment]
@stefanprodan let's record this in an issue and discuss details there.

**Pull request merged**
