### PR TITLE
Fix "Notification API reference" title

### PR DESCRIPTION
**Pull request by gertux**
The title of the Notification API reference reads "Kustomize API reference".
Seems obvious where the template was copied from ;-)

### CODE REVIEW

**Comment by stefanprodan** [comment]
@gertux you need the run the code-gen with `make test` and then commit the changes.

**Comment by stefanprodan** [comment]
@gertux please squash your commits into a single one and signoff your commit.

**Comment by gertux** [comment]
> @gertux please squash your commits into a single one and signoff your commit.

OK, will do, but I'll first read the contributing docs a little better

**Comment by stefanprodan** [comment]
Like most Linux Foundation projects we require contributors to signoff their commits, more info here  https://github.com/fluxcd/community/blob/main/CONTRIBUTING.md

**Pull request closed without merging**
