### PR TITLE
Bitbucket docs

### LINKED ISSUE #185: Git commit status into dev deploy
### Describe the bug

We want to upgrade our flux to flux v2 deployed into multiple clusters, all point same bitbucket repo. Seem like bootstrap using a git bitbucket repo is no ready yet. 

Flux v1 tag the commit of the repo that are using. We are looking for similar function into flux v2, but only find the commit status solution to do similar function.

To deploy flux we are using dev mode, but when try to configure alerts, we get these errors:

```
2021-04-21T09:54:21.284Z info Kustomization/podinfo.flux-system - Dispatching event: Update completed
2021-04-21T09:54:21.744Z error Kustomization/podinfo.flux-system - failed to send notification 401 Unauthorized
```

### To Reproduce

Steps to reproduce the behaviour:

1. Provide Flux install instructions
```
flux install --network-policy=true --watch-all-namespaces=true --namespace=flux-system

flux create source git name1 --url=https://bitbucketfactory.repo/route/to/repo.git --branch=master --interval=1m --username=user --password=pass

flux create kustomization name2 --source=name1 --path="./dev/services" --prune=true --interval=5m
```
podinfo (public kustomize copied into "./install/podinfo)
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: podinfo
  path: ./install/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: name1
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: podinfo
  timeout: 1m
```
secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: provider-secret
  namespace: flux-system
data:
  token: base64name:base64pass
```
alert and alert-provider

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: bitbucket
  address: https://bitbucketfactory.repo/route/to/repo.git
  secretRef:
    name: provider-secret

---

apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: podinfo
  namespace: flux-system
spec:
  providerRef:
    name: flux-system
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: podinfo
      namespace: flux-system
```

### Expected behavior

We want that the commit will marked when flux v2 are using it into every cluster.

### Additional context

- Kubernetes version: 1.17.12
- Git provider: bitbucket

Below please provide the output of the following commands:

```cli
flux --version: 0.12.1
flux check

► checking prerequisites
✗ flux 0.12.1 <0.12.3 (new version is available, please upgrade)
✔ kubectl 1.19.0 >=1.18.0-0
✔ Kubernetes 1.17.12-eks-7684af >=1.16.0-0
► checking controllers
✔ all checks passed

```

### PR DESCRIPTION
**Pull request by SomtochiAma**
Closes #185 

Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>

### CODE REVIEW

**Comment by kingdonb** [comment]
I have tested the Receiver against the `generic` webhook and it works with Bitbucket cloud. There are some differences here between BB Cloud and BB Server / on-premise from Atlassian. I've been meaning to capture this info and get it added to the doc. I hadn't worked through commit status at all, which is what you have documented here (🎉) – I only went for `Receiver`.

Would it help at all if I add something about that, so we can complete the notification-controller docs related to Bitbucket in this PR? (I can send it to you as a PR against your branch)

**Comment by SomtochiAma** [comment]
@kingdonb I think that's a great idea

**Review by stefanprodan — APPROVED** [review]

**Review by kingdonb — APPROVED** [review]
LGTM, please consider including the change I posted to https://github.com/SomtochiAma/notification-controller/pull/1

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @SomtochiAma please squash.

**Pull request merged**
