### PR TITLE
Remove checks for empty user and channel parameters in Rocket notifier

### LINKED ISSUE #594: Rocket username and channel are mandatory but not documented
The documentation for the Rocket notification provider says the following:

> To configure a Provider for Rocket, create a Secret with [the address](https://fluxcd.io/flux/components/notification/provider/#address-example) set to the Rocket [webhook URL](https://docs.rocket.chat/guides/administration/admin-panel/integrations#incoming-webhook-script), and a rocket Provider with a [Secret reference](https://fluxcd.io/flux/components/notification/provider/#secret-reference).

However, the provider code checks for the presence of both username and channel properties as well and will error leaving it in a not ready state if these are not provided:
```
	if username == "" {
		return nil, errors.New("empty Rocket username")
	}

	if channel == "" {
		return nil, errors.New("empty Rocket channel")
	}
```

### PR DESCRIPTION
**Pull request by GJKrupa**
closes #594

### CODE REVIEW

**Comment by makkes** [comment]
Please [sign-off each commit](https://github.com/fluxcd/flux2/blob/main/CONTRIBUTING.md#certificate-of-origin) and [properly format your commit message](https://github.com/fluxcd/flux2/blob/main/CONTRIBUTING.md#format-of-the-commit-message).

**Comment by GJKrupa** [comment]
Commit message replaced as requested

**Review by makkes — COMMENTED** [review]
LGTM. Please squash the two commits into one.

**Comment by GJKrupa** [comment]
Squashed

**Review by makkes — APPROVED** [review]

**Review by stefanprodan — APPROVED** [review]

**Pull request merged**
