### PR TITLE
Add Terraform event source kind

### PR DESCRIPTION
**Pull request by k0da**
Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

### CODE REVIEW

**Comment by stefanprodan** [comment]
The Terraform Kind is not an a Flux CRD, if you want  to enable notifications for 3rd party controllers see https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-notifications-for-third-party-controllers

**Comment by k0da** [comment]
Sorry, I don't have kustomize controller deployed.  Wouldn't it be easier to relax validation here? 
It is a little bit an overkill to add a new type.

**Comment by stefanprodan** [comment]
@k0da you do a `kubectl patch` for each patch in https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-notifications-for-third-party-controllers, his is not only about adding Terraform to the CRD but also about RBAC.

**Comment by stefanprodan** [comment]
> Wouldn't it be easier to relax validation here?

The validation is only half the problem, notification-controller needs to have read access to that Kind at cluster level too. We have no plans on given this controller cluster-admin, or allow it to read any random object from the cluster.

**Comment by k0da** [comment]
@stefanprodan but this can be fixed on tf-controller side. A chart can bring a role and binding.

**Pull request closed without merging**
