### PR TITLE
Add config checksum from event metadata to rate limiting key

### PR DESCRIPTION
**Pull request by matheuscscp**
Builds on https://github.com/fluxcd/notification-controller/pull/517 and https://github.com/fluxcd/pkg/pull/544

Fixes https://github.com/fluxcd/helm-controller/issues/678 alongside https://github.com/fluxcd/helm-controller/pull/681 and https://github.com/fluxcd/pkg/pull/544

### CODE REVIEW

**Comment by hiddeco** [comment]
First wondered if the more generic approach to this would be to pass on the generation of the involved object, and take this into account. However, this would not cover for things which may produce different results due to to e.g. contents of referenced Secrets and/or ConfigMap changing (as could be the case for Helm values).

**Comment by matheuscscp** [comment]
> First wondered if the more generic approach to this would be to pass on the generation of the involved object, and take this into account. However, this would not cover for things which may produce different results due to to e.g. contents of referenced Secrets and/or ConfigMap changing (as could be the case for Helm values).

But nice catch! We could also add the object generation anyways :thinking: Should I update this PR or open another one?

**Comment by matheuscscp** [comment]
@hiddeco What are the next steps here now that https://github.com/fluxcd/pkg/pull/544 got merged?

**Comment by hiddeco** [comment]
Update the other PRs to properly working with this, while the actual tagging of the event API package is waiting you can use a revision from main in the PRs.

**Comment by matheuscscp** [comment]
Superseded by https://github.com/fluxcd/notification-controller/pull/530

**Pull request closed without merging**
