### PR TITLE
Switch to controller-runtime metadata client

### PR DESCRIPTION
**Pull request by SomtochiAma**
Follow-up: #325 

Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>

### CODE REVIEW

**Comment by SomtochiAma** [comment]
Yes we can, but we still have to provide the group version and kind

**Comment by stefanprodan** [comment]
Ok let’s use the metadata client for all operations.

**Comment by stefanprodan** [comment]
@SomtochiAma can you please add tests for receiver annotations? We only test the reconciliation but not the webhook handler.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @SomtochiAma 🌷

**Pull request merged**
