### PR TITLE
Add object kind to messages

### LINKED ISSUE #120: Adding object kind to notifications
In some notification providers like Teams it is not always clear from which object type the notifications origin.

In Slack the originating controller is used as a username of the message, but in Teams the username is set by the webhook configuration.

Would it be possible to add the Kind of the causing object to the objName that is part of the message. 
E.g. as pre-/ or postfix like
`<Kind>/<name>.<namespace>`
or
`<name>.<namespace>.<kind>` (to stay in hostname notation)

(from https://github.com/fluxcd/flux2/issues/710 )

### PR DESCRIPTION
**Pull request by SomtochiAma**
This pull request adds the object kind of the source of the notification to the message.
The format is `<kind>/<name>.<namespaces>`
Fixes #120 

Signed-off-by: Somtochi Onyekwere <somtochionyekwere@gmail.com>

### CODE REVIEW

**Comment by phillebaba** [comment]
Can we mimic the current implementation of the git notifications? In those providers the kind is already included and we lowercase all of the text.

```
 kustomization/apps-dev — reconciliation succeeded
```

**Comment by SomtochiAma** [comment]
> Should we mimic the current implementation of the git notifications? In those providers the kind is already included and we lowercase all of the text.
> 
> ```
>  kustomization/apps-dev — reconciliation succeeded
> ```

@stefanprodan What do you think? We should definitely maintain a consistent format

**Comment by stefanprodan** [comment]
Yes the kind should be lowercase, this is also consistent with kustomize-controller apply logs.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @SomtochiAma

**Pull request merged**
