### PR TITLE
Custom Git Commit Status Prefix 

### PR DESCRIPTION
**Pull request by clarkdoan**
Resolves: #194 

### Problem
When setting a git commit status the controller only uses the  `event.InvolvedObject.Kind` and  `event.InvolvedObject.Name` to generate the status' context. This does not allow multiple clusters to update the commit status if they use the same Kustomization name. 

### Proposed Solution
The event that is passed to the `formatNameAndDescription` function contains a `Metadata` field. 

The `AlertSpec` contains a `Summary` field which is used as a `Short description of the impact and affected cluster.`

The event handler copies the value of the `Summary` field from the `AlertSpec` to the `Metadata` field of the event. 

This PR checks the value of the `Metadata` field to see if there is a `summary` key. If the key exists then the summary value will be prepended to the context of the commit status. This will allow the user to set the prefix of the commit status.

### CODE REVIEW

**Review by stefanprodan — COMMENTED** [review]
Please change the `Summary` description in code and run `make test` then commit the generated CRDs. Append this to the field description: "For commit status updates, this field is used to prefix the status message.".

**Comment by phillebaba** [comment]
We need to do some testing with this feature regarding different provider length constraints and format constraints, as this will allow users to inject arbitrary text into the status ID.

**Comment by stefanprodan** [comment]
@phillebaba I think we should trim the summary to a small number of characters, as you said we need to determine which number that is.

**Comment by phillebaba** [comment]
Github has a limit of 140 last time I hit this issue but is not documented. Gitlab has something similar while Azure DevOps has a much larger limit. The issue is that none of these limits are documented.

**Comment by phillebaba** [comment]
I would actually prefer to hold off on this PR and instead implement a more generic solution as proposed here.
https://github.com/fluxcd/flux2/discussions/1529

**Pull request closed without merging**
