### PR TITLE
Add Philip Laine to maintainer list

### PR DESCRIPTION
**Pull request by phillebaba**

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
LGTM 💯 

Thanks @phillebaba for all your contributions 🏅

**Review by hiddeco — APPROVED** [review]
Well deserved :100:

**Review by squaremo — APPROVED** [review]
:+1: :100:

**Comment by simongottschlag** [comment]
Congratulations @phillebaba! Well deserved 😁👍💯

**Pull request merged**
